### ISSUE TITLE
Single cell optimization for neocortical model

### ISSUE THREAD

**Issue by jdcourcol** [cnr-ibf-pa/hbp-bsp-issues#80] opened 2017-11-20 12:40 UTC
Deliver a single cell optimization done with bluepyopt consistent with current SP6 models for neocortical models.

**Comment by jdcourcol** [comment] 2017-11-20 12:40
Currently no neocortical models are available to reproduce with BluePyOpt

**Comment by alex4200** [comment] 2017-12-18 12:18
Duplicate of #93

**Closed by alex4200** 2017-12-18 12:18 UTC
Labels: Topic_SingleCellBuilding, Type_Feature
