### ISSUE TITLE
Granular Cells in BlueNaaS

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#330] opened 2018-07-31 09:03 UTC
## Summary
  
Aspect | Detail
------------ | -------------
Summary | Cerebellar granular cells simulation with BlueNaaS. The export of custom sectionlist is now working and, with the temperature as an option on the GUI, the simulation are fine.
Usecase Group |
State | New
Expert | @SteMasoli @rizland 
Scientific User | All
Deadline | 
Target audience | All
Target interface | GUI
HPC Requirements | No. 
Dependencies | BlueNaaS
Nominal runtime |
  
## List of features
Cerebellar granule cells, three different complexities, will be uploaded to BlueNaaS GUI. The users will be able to do simulations, graph etc. as is already possible for various neurons from both the cortex and the hippocampus.

 ### Tasks
 
- [ ] Add the cells to the BSP to be accessible like the Hyppocampal neurons. Needs information on how to do it. See #349 
- [ ] Export the mouse Purkinje cell.
- [ ] Export the now final new granule cell model.
 
## Acceptance Criteria
- Perform BlueNaaS simulation with Granule Cells (3 complexities) and a mouse Purkinje cell.

  
### System
The requirement, both in terms of hardware and software, are the same as BlueNaaS.

  
### Performance
Mono and multi compartmental models are simulated in a matter of seconds.

**Comment by SteMasoli** [comment] 2018-09-02 19:42
Waiting for Werner to modify BluePyOpt Neuron template exporter.

**Comment by SteMasoli** [comment] 2018-09-24 09:56
The exporter was updated by Werner Van Geit and it does the export into NaaS format.
The single compartmental model can be uploaded but there is still a small issue with it. The multicompartmental model does not upload at all. Working on it.

**Comment by alex4200** [comment] 2018-10-08 10:02
@SteMasoli requested change to BlueNaaS (@genric ; temperature dependency).

**Comment by genric** [comment] 2018-10-08 11:19
So, if I understand correctly, you want temperature to be exposed as a configurable parameter, let's say with default value of 34? @wvangeit any opinion on that?

**Comment by SteMasoli** [comment] 2018-10-09 11:10
> you want temperature to be exposed as a configurable parameter
Yes. The MOD files we use are temperature dependent so the results are inflenced by it.

**Comment by genric** [comment] 2018-10-09 12:59
I've updated the app. @alex4200 could you please do some regression testing to make sure it is ok, thanks!

**Comment by genric** [comment] 2018-10-10 08:12
Thanks @alex4200 
I tried to reproduce (1) but all the scenarios you described work fine for me: I'm able to download the traces. Regarding (2) if you have a better suggestion for the temperature range constraint please let me know.

**Comment by SteMasoli** [comment] 2018-10-10 11:46
@genric  Thank you.
I can suggest a range between 20/25 (room temperature for many experiments) and 37 (physiological temperature).
I cannot use a comma in the amp[nA] field to set 0,01nA. Previously was ok.

**Comment by genric** [comment] 2018-10-16 08:35
@SteMasoli I'll update the range to be [20:40]
I don't think comma was ever working, it was always the dot as far as I can remember.

**Comment by genric** [comment] 2018-10-17 12:30
I've updated the deployment with new temperature range constraint.

**Comment by SteMasoli** [comment] 2018-10-22 08:38
@genric "I don't think comma was ever working, it was always the dot as far as I can remember."
Ok. Since the granule cells are very sensitive i have to set picoampere currents.  
For example 0.01nA (10pA) cannot be define. It returns "holding current is required".

**Comment by SteMasoli** [comment] 2018-10-22 08:43
@genric "I don't think comma was ever working, it was always the dot as far as I can remember."
Cannot set the current injection to something different that nA. If i try with 0.01nA (10pA) it says "amp is required". The same happens with the holding current.

**Comment by genric** [comment] 2018-10-22 09:45
@SteMasoli , correct, units are fixed and current is nA. The browser should allow only to enter digits and a dot for the current value.

**Comment by SteMasoli** [comment] 2018-11-03 19:44
@genric Just tested it, with the single section granule cell, and it works very well. Thank you.
About the current value, i can set it using Firefox 63 under linux. I cannot do it with Firefox 63 under window 7/8. I'll check other combinations.

Now i'll focus on exporting a valid version of the multi compartmental granule cell model.

**Comment by SteMasoli** [comment] 2018-11-03 20:52
@wvangeit Multi compartmental granule cell modified following your advise. It works.

**Comment by alex4200** [comment] 2018-11-05 08:39
@SteMasoli I can test the issue regarding entering digits and the dot on a windows 10 computer system on Wednesday.

**Comment by alex4200** [comment] 2018-11-07 13:06
@genric: I have tested the input boxes on BlueNaaS, and it looks like I also can enter the following characters: "^" and "`" and other characters after I press the diaeresis key [see here](https://en.wikipedia.org/wiki/Diaeresis_(diacritic)).

![screen shot 2018-11-07 at 14 06 27](https://user-images.githubusercontent.com/12729291/48133199-55f6a780-e296-11e8-920e-e6477604a83a.png)

But I consider that not of high importance...

**Comment by alex4200** [comment] 2018-11-19 13:32
@SteMasoli @rizland Does the ticket #349 cover the items described in this ticket? In other words, can THIS ticket be closed?

**Comment by SteMasoli** [comment] 2018-11-20 12:16
The exporter and resulting models are fine so, yes @alex4200 this one can be closed.

**Comment by SteMasoli** [comment] 2019-05-26 10:20
Hi.
There is something wrong with BlueNaaS. @genric 

1) It is very slow to load the models, both from cerebellum and hippocampus. @alex4200 
It get stuck after a while, before showing the morphology and the topology.
Is happening with Firefox under linux and win 7 (me) and Chrome on win 10 @rizland .

2) I was uploading a new series of models and they got stuck in a loop. 
Locally the code run fine, so i think the issue is related to the previous point.

**Comment by alex4200** [comment] 2019-05-27 11:18
@SteMasoli I also see problems with the BlueNaaS. I created a ticket.

**Comment by SteMasoli** [comment] 2019-06-09 08:29
Hi.
The models are working fine with Firefox V67.0 under Linux and not with Firefox V67.0.1 under win7. @genric  @alex4200 

Instead the models i need to upload remain stuck in an endless "loading loop". At which email can i send one model to be checked?

**Comment by genric** [comment] 2019-06-12 08:26
@SteMasoli based on our email exchange I'm assuming it worked for you and I'm closing this. Feel free to reopen it if there are problems remaining. Thanks!

**Comment by SteMasoli** [comment] 2019-06-19 08:29
Hi.
I'm sorry to have to reopen this issue. @genric 
I have uploaded my last model and, after four trials, it cannot be simulated for more than 1750-1780ms.
After this threshold, the top right part of the pages reports "Disconnected. Please reload the page to reconnect".
The model temporary location:
https://blue-naas.humanbrainproject.eu/#/model/SM_GrC2019_accellerating

Best

**Comment by genric** [comment] 2019-06-20 11:49
@SteMasoli no problem. I'll have a look...

**Comment by genric** [comment] 2019-06-21 14:41
@SteMasoli the simulation with the variable time step is quite slow for this model, so apparently it was reaching connection timeout before completing the simulation. I fixed now how timeouts are handled, so you should be able to run the simulation to completion.

**Comment by SteMasoli** [comment] 2019-06-24 09:47
Tested it, everything fine.
Thank you

**Closed by SteMasoli** 2019-06-24 09:47 UTC
Labels: Type_New
