### ISSUE TITLE
Can not load Jupyter Notebooks on Collab

### ISSUE THREAD

**Issue by sasaray** [cnr-ibf-pa/hbp-bsp-issues#495] opened 2019-12-04 10:45 UTC
### Expected behavior
Jupyter Notebooks can bee loaded and run

### Actual Behavior (please include screenshot if possible)

Me and @szkali  can not load any Jupyter Notebook on The Collab. We both get the following error message:

"Error loading the notebook
Your session is expired and it's not possible to load your notebook from the Collab storage."
![Collab_error](https://user-images.githubusercontent.com/14124437/70136044-86706700-168b-11ea-8674-af11cf07866b.PNG)

**Comment by alex4200** [comment] 2019-12-04 10:49
[The Collab team] purged some refresh tokens in order to improve the performance of the MITREid Connect server. It seems it did not work as intended and had some side effects.

This issue seems to affect EVERY collab user. I have asked the Collab team to reset EVERY container.

**Comment by alex4200** [comment] 2019-12-04 13:53
@sasaray @szkali Can you please try again? The issue might be solved. 

Maybe you need to log out and log in again. Also note: As the container has been reset, some packages you are using by default must be re-installed. 

if it works, please close this ticket

**Comment by sasaray** [comment] 2019-12-04 14:42
@alex4200 It works fine. Thanks a lot!

**Closed as completed** 2019-12-04 14:42 UTC
