### ISSUE TITLE
PizDaint - /core anonymous 

### ISSUE THREAD

**Issue by antonelepfl** [cnr-ibf-pa/hbp-bsp-issues#537] opened 2020-04-17 10:05 UTC
Hi @BerndSchuller I'm getting some anonymous information like this:

<img width="898" alt="Screenshot 2020-04-17 at 12 02 05" src="https://user-images.githubusercontent.com/24406041/79557765-6aea8380-80a3-11ea-9dce-f7b42ae13bdc.png">

Where I should get something like:

<img width="786" alt="Screenshot 2020-04-14 at 13 47 40" src="https://user-images.githubusercontent.com/24406041/79557786-750c8200-80a3-11ea-9786-196fac29e7b5.png">

is this related to your https://github.com/cnr-ibf-pa/hbp-bsp-issues/issues/536#issuecomment-613422631 ?

**Comment by BerndSchuller** [comment] 2020-04-17 10:11
no

you are authenticated correctly (the "dn": ..." field is correct)

the user mapping (role and UID) is done by the CSCS installation. You should ask Fabio Verzelloni at CSCS

**Comment by antonelepfl** [comment] 2020-04-17 13:24
Verzelloni Fabio <fverzell@cscs.ch> fixed the issue.

**Comment by clupascu** [comment] 2021-01-25 13:02
I have the same issue now.

**Comment by BerndSchuller** [comment] 2021-01-25 13:49
Authentication seems to work (for collab2 at least) - what exactly do you get from the /rest/core endpoint? 
To fix the user mapping ("role" and "xlogin") you'd need to contact Fabio Verzelloni fverzell@cscs.ch

**Comment by clupascu** [comment] 2021-01-25 13:59
I get this on collab2
{'server': {'jobSubmission': {'message': '', 'enabled': True},
  'credential': {'dn': 'CN=ronco.cscs.ch,O=ETH Zuerich,L=Zuerich,ST=Zuerich,C=CH',
   'issuer': 'CN=QuoVadis Global SSL ICA G2,O=QuoVadis Limited,C=BM'},
  'externalConnections': {'UFTP Server': 'OK',
   'XUUDB attribute source': 'OK',
   'Gateway': 'OK',
   'Registry': 'OK',
   'TSI 1': 'OK'},
  'trustedCAs': ['CN=unity-jsc.fz-juelich.de,OU=JSC,O=Forschungszentrum Juelich GmbH,L=Juelich,ST=Nordrhein-Westfalen,C=DE',
   'CN=QuoVadis Global SSL ICA G2,O=QuoVadis Limited,C=BM',
   'CN=DFN-Verein Global Issuing CA,OU=DFN-PKI,O=Verein zur Foerderung eines Deutschen Forschungsnetzes e. V.,C=DE'],
  'version': '8.0.2',
  'trustedSAMLIssuers': ['CN=unity-jsc.fz-juelich.de,OU=JSC,O=Forschungszentrum Juelich GmbH,L=Juelich,ST=Nordrhein-Westfalen,C=DE']},
 '_links': {'storages': {'href': 'https://brissago.cscs.ch:8080/DAINT-CSCS/rest/core/storages'},
  'client-server-transfers': {'href': 'https://brissago.cscs.ch:8080/DAINT-CSCS/rest/core/client-server-transfers'},
  'transfers': {'href': 'https://brissago.cscs.ch:8080/DAINT-CSCS/rest/core/transfers'},
  'jobs': {'href': 'https://brissago.cscs.ch:8080/DAINT-CSCS/rest/core/jobs'},
  'factories': {'href': 'https://brissago.cscs.ch:8080/DAINT-CSCS/rest/core/factories'},
  'sites': {'href': 'https://brissago.cscs.ch:8080/DAINT-CSCS/rest/core/sites'},
  'registries': {'href': 'https://brissago.cscs.ch:8080/DAINT-CSCS/rest/core/registries'},
  'storagefactories': {'href': 'https://brissago.cscs.ch:8080/DAINT-CSCS/rest/core/storagefactories'}},
 'client': {'role': {'selected': 'anonymous', 'availableRoles': ['anonymous']},
  'dn': 'UID=carmen.lupascu@ibf.cnr.it',
  'xlogin': {}}}
I contacted Fabio to fix the user mapping. Thank you @BerndSchuller

**Comment by clupascu** [comment] 2021-01-25 14:00
Fabio just replied that my user is correctly mapped, but they are having some issue with the pem certificate of the CA.
He will let me know as soon as the problem is solved.

**Comment by clupascu** [comment] 2021-01-26 12:43
Fabio solved the issue. I am closing again the ticket.

**Closed as completed by clupascu** 2021-01-26 12:43 UTC
