### ISSUE TITLE
blue-nass hangs if attached voltage trace is longer than the simulation tstop

### ISSUE THREAD

**Issue by orena1** [cnr-ibf-pa/hbp-bsp-issues#392] opened 2019-02-17 12:54 UTC
### Expected behavior
I assume that when the simulation stops (no matter when) it should show the attached voltage trace.

### Actual Behavior
It hangs.
### Steps to reproduce the problem

Add this file to blue-nass and click start simulation (with tstop=1000):
[cell0603_03_model_476.zip](https://github.com/cnr-ibf-pa/hbp-bsp-issues/files/2872958/cell0603_03_model_476.zip)

@genric 
Thanks,

**Comment by alex4200** [comment] 2019-02-18 06:45
I cannot reproduce this behavior, I get the traces and can download them. 

However, the data in the csv file look a bit strange:

```
4,0.064,,,-87.285,-87.035,-86.508
5,0.075,-59.489644783789274,-65.08615062567164,,,
6,0.09999999999999999,-55.888200349708576,-65.08413158775365,,,
7,0.124,,,-87.136,-86.975,-86.585
```

**Comment by orena1** [comment] 2019-02-18 08:35
Hi @alex4200 
I'm looking at the file (it's actually a .dat file and not a csv) and I do not see the same problem as you see:
![image](https://user-images.githubusercontent.com/8983713/52937817-d1bdc100-3368-11e9-8c6e-0d1907786207.png)

**Comment by orena1** [comment] 2019-02-18 10:00
But it seems that it does not hang anymore. Maybe I just needed to wait some more time. I assume we can close this ticket. Sorry

**Comment by genric** [comment] 2019-02-18 10:16
If you change the column names to have soma segment 0 like the following:
time,soma[0]_0_exp0,soma[0]_0_exp1,soma[0]_0_exp2
Then you'll get soma highlighted when you hover the trace :)
Other than that works for us as well, so closing it.

**Closed as completed by genric** 2019-02-18 10:16 UTC
Labels: Type_BUG

**Comment by orena1** [comment] 2019-02-18 10:19
Thanks for the tip
