### ISSUE TITLE
BlueNaaS: does not load parameters

### ISSUE THREAD

**Issue by orena1** [cnr-ibf-pa/hbp-bsp-issues#394] opened 2019-02-17 16:53 UTC
This video shows the problem in detail:

![complicatedlittlekitfox-size_restricted](https://user-images.githubusercontent.com/8983713/52916204-27e92080-32e5-11e9-8e76-45c30690c277.gif)

https://youtu.be/FEMuoOSO1N0

Thanks,
@genric

**Comment by genric** [comment] 2019-02-18 09:34
Hi @orena1 
If you modify already loaded url, you'll have to click reload to correctly process the query params. As hitting enter doesn't reload the app and query params are processed during app initialization.
If you follow the link directly, with all params predefined, it should work: https://blue-naas.humanbrainproject.eu/#/url/human_cells/cell0603_03_model_476.zip?delay=120.33&vinit=-86.1&dt=.02&amp=0.7&tstop=1111&dur=1000
Although in the video it looks like you are doing this... so I'm a bit confused as I was not able to reproduce it.

**Comment by genric** [comment] 2019-02-18 09:36
Hmm, I think it has something to do with the model format, I think it overrides those values: vinit and dt.

**Comment by orena1** [comment] 2019-02-18 10:19
Anything we can do?

**Comment by genric** [comment] 2019-02-18 10:21
You can change your model to use the format specified on the left here: https://blue-naas.humanbrainproject.eu/
But if you wait a bit I'll fix the other one not to override the params when they have been explicitly provided.

**Comment by orena1** [comment] 2019-02-18 10:32
I'll wait, thank you very much

**Comment by orena1** [comment] 2019-02-18 12:38
Another thing, @genric  how do I set the temperature? 
Thanks

**Comment by genric** [comment] 2019-02-18 13:03
Thought nobody will ask :) as it is recent addition to the configuration. Will fix that with the next release if you don't mind. Or, if it is urgent, I can make another one in an hour.
I just deployed the fix for the current issue, so please retry.

**Comment by orena1** [comment] 2019-02-18 13:12
Thanks @genric , its not urgent, we will build the live papers with all the variables in the links. So that whenever the new versions will be deployed, it will work correctly.

**Comment by genric** [comment] 2019-02-18 13:17
Ok, then I'll commit the fix and it will arrive when the new version is deployed.
The param will be same as in NEURON: **celsius**

**Comment by genric** [comment] 2019-02-20 08:53
@orena1 @alex4200 this can be retested and please feel free to close the issue if it works as expected, thanks.

**Comment by alex4200** [comment] 2019-02-20 09:28
Seems to work for different models (except temperature as stated).

**Closed as completed by alex4200** 2019-02-20 09:28 UTC
Labels: Type_BUG
