### ISSUE TITLE
First prototype of subcellular experiment

### ISSUE THREAD

**Issue by jdcourcol** [cnr-ibf-pa/hbp-bsp-issues#307] opened 2018-06-01 10:23 UTC
This first prototype will have the following steps:
neuron selection -> synapse selection -> protein selection.

Further steps will be implemented in a different ticket

**Comment by alex4200** [comment] 2018-09-12 13:16
@jdcourcol @pgetta : Can you please update the proper milestone for SGA2 (M06, M12 etc)?

Thanks

**Comment by alex4200** [comment] 2019-04-02 11:56
Duplicate of #327

**Closed by alex4200** 2019-04-02 11:56 UTC
Labels: Topic_Subcellular, Type_New
