### ISSUE TITLE
Get notification if a cloned notebook has been changed

### ISSUE THREAD

**Issue by clupascu** [cnr-ibf-pa/hbp-bsp-issues#364] opened 2019-01-08 09:00 UTC
### Expected behavior
The user should be notified once a cloned notebook has been changed
### Actual Behavior (please include screenshot if possible)
Currently once a notebook is cloned it is not automatically updated when the original notebook has changed

**Comment by alex4200** [comment] 2019-04-02 12:58
Duplicate of #382

**Closed by alex4200** 2019-04-02 12:58 UTC
Labels: Type_Usability
